const Discord = require("discord.js");
let botconfig = require("../botconfig");
let cyan = botconfig.cyan;
module.exports.run = async (bot, message, args) => {
	let regel = new Discord.RichEmbed().setColor(cyan).addField("Bot Commando's", "**" + "---------" + "**" + "\n" + "!verwijder" + "\n" + "Wordt gebruikt om aan te geven dat een dealer verwijderd moet worden. Vervang Habbo door een Habbo naam en Badge door de naam van een badge." + "\n" + "**" + "!verwijder Habbo Badge1 Badge2 Badge3 " + "**" + "\n" + "**" + "---------" + "**" + "\n" + "!meld" + "\n" + "Wordt gebruikt jezelf of een andere crew afwezig te melden. Vervang naam door de naam van de persoon en reden met de reden + eventuele datums." + "\n" + "**" + "!meld naam reden " + "**" + "\n" + "**" + "---------" + "**" + "\n" + "!zeg" + "\n" + "Wordt gebruikt om via de bot een bericht te plaatsen. Vervang bericht met een eigen gekozen bericht." + "\n" + "**" + "!zeg bericht " + "**" + "\n" + "**" + "---------" + "**" + "\n" + "!vote" + "\n" + "Wordt gebruikt om een stem teller te starten." + "\n" + "**" + "!vote " + "**" + "\n").addField("Overige Commando's", "**" + "---------" + "**" + "\n" + "!waarschuwing" + "\n" + "Wordt gebruikt om een dealer een waarschuwing te geven. Vervang Habbo door een Habbo naam." + "\n" + "**" + "!waarschuwing Habbo " + "**" + "\n" + "**" + "---------" + "**" + "\n" + "!verwijderwaarschuwing" + "\n" + "Wordt gebruikt om 1 waarschuwing per keer te verwijderen bij een dealer. Vervang Habbo door een Habbo naam." + "\n" + "**" + "!verwijderwaarschuwing Habbo " + "**" + "\n" + "**" + "---------" + "**" + "\n" + "!all" + "\n" + "Wordt gebruikt om een lijst te zien met alle waarschuwingen." + "\n" + "**" + "!all " + "**" + "\n" + "**" + "---------" + "**" + "\n" + "!pot" + "\n" + "Wordt gebruikt om de vergoedingspot bij te werken. Vervang 1 door het nieuwe aantal en reden met de reden van de verandering. Gebruik !aantalpot voor de huidige inhoud." + "\n" + "**" + "!pot 1 reden " + "**" + "\n").addField("Bot Commando's vervolg", "**" + "---------" + "**" + "\n" + "!accepteer" + "\n" + "Wordt gebruikt om een herinnering te maken dat een dealer moet worden aangenomen. Vervang Habbo door een Habbo naam en Badge door de naam van een badge." + "\n" + "**" + "!accepteer Habbo Badge1 Badge2 Badge3 " + "**" + "\n" + "**" + "---------" + "**" + "\n" + "!pf" + "\n" + "Wordt gebruikt om de profielfoto van een persoon in het groot te zien. Vervang gebruiker door een persoon in de server." + "\n" + "**" + "!pf @gebruiker " + "**" + "\n" + "**" + "---------" + "**" + "\n" + "!delete" + "\n" + "Wordt gebruikt om meerdere berichten in 1x te verwijderen. Vervang 1 door het aantal berichten." + "\n" + "**" + "!delete 1 " + "**" + "\n" + "**" + "---------" + "**" + "\n" + "!ontslagen" + "\n" + "Wordt gebruikt om aan te geven dat een dealer is ontslagen. Vervang Habbo door de Habbo naam en reden met de reden." + "\n" + "**" + "!ontslagen Habbo reden " + "**" + "\n" + "**" + "---------" + "**" + "\n");
	message.delete().catch();
	message.channel.send(regel);
}
module.exports.help = {
	name: "commands"
}